POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blogs: What are they good for?",
    "author": "Jim Riggins",
    "url": "https://www.blogsrus.com/jimriggins/blogs-what-are-they-good-for",
    "likes": 13
}